-- Create Inventory Table
CREATE TABLE inventory (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    quantity NUMBER NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    exp_date DATE NOT NULL
);

-- Create Prescriptions Table
CREATE TABLE prescriptions (
    prescription_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(50) NOT NULL,
    drug_id NUMBER NOT NULL,
    dosage VARCHAR2(50) NOT NULL,
    issue_dt DATE NOT NULL,
    FOREIGN KEY (drug_id) REFERENCES inventory(id)
);

-- Insert sample data into Inventory Table
INSERT INTO inventory (name, quantity, price, exp_date) VALUES ('Aspirin', 100, 5.99, TO_DATE('2024-12-31', 'YYYY-MM-DD'));
INSERT INTO inventory (name, quantity, price, exp_date) VALUES ('Paracetamol', 50, 3.99, TO_DATE('2024-10-15', 'YYYY-MM-DD'));

-- Procedure to Add Drug to Inventory
CREATE OR REPLACE PROCEDURE add_drug (
    p_name IN VARCHAR2,
    p_quantity IN NUMBER,
    p_price IN NUMBER,
    p_exp_date IN DATE
) AS
BEGIN
    INSERT INTO inventory (name, quantity, price, exp_date)
    VALUES (p_name, p_quantity, p_price, p_exp_date);
    COMMIT;
END add_drug;
/

-- Procedure to Issue Prescription
CREATE OR REPLACE PROCEDURE issue_prescription (
    p_patient_id IN VARCHAR2,
    p_drug_id IN NUMBER,
    p_dosage IN VARCHAR2,
    p_issue_dt IN DATE
) AS
BEGIN
    INSERT INTO prescriptions (patient_id, drug_id, dosage, issue_dt)
    VALUES (p_patient_id, p_drug_id, p_dosage, p_issue_dt);
    COMMIT;
END issue_prescription;
/
-- Adding a drug to the inventory
EXEC add_drug('Ibuprofen', 200, 7.50, TO_DATE('2025-01-01', 'YYYY-MM-DD'));

-- Issuing a prescription
EXEC issue_prescription('12345', 1, '2 tablets', TO_DATE('2024-06-01', 'YYYY-MM-DD'));
